---
title: "Hiriote_and_Pattarapanitchai_2016"
output: html_document
---

# Functions

## To calculate true CCC

```{r}
True_CCC <- function(var_1, var_2, cov_12, mu_1, mu_2){
    return(
        (2*cov_12)/(var_1 + var_2 + (mu_1 - mu_2)^2)
    )
}
```

## To calculate true CCCM

```{r}
True_CCCM <- function(M, U, V){
    tr <- function(x){x |> diag() |> sum()}
    d <- dim(U)[1]
    
    MMt <- M %*% t(M)
    
    numerator <- tr(V) * (sum(U) - tr(U))
    denominator <- ((d-1) * tr(U) * tr(V)) + (d*tr(MMt)) - sum(MMt)
    
    return(
        numerator/denominator
    )
}
```

# Simulation setting

```{r}
mu_1_vec <- c(4,7,8,10,12)
mu_2_vec <- c(6,9,10,12,14)
sigma_sq_1 <- 1
sigma_sq_2 <- 1.25
rho_r <- 0.6
tau_sq_vec <- c(1,3.5,5,3.2,4)
rho_c_vec <- c(0)
```

# calculate CCCs

```{r}
for(i in 1:5){
    True_CCC_i_value <- True_CCC(
        var_1 = sigma_sq_1 * tau_sq_vec[i],
        var_2 = sigma_sq_2 * tau_sq_vec[i],
        cov_12=sqrt(sigma_sq_1) * sqrt(sigma_sq_2) * rho_r * tau_sq_vec[i],
        mu_1  = mu_1_vec[i],
        mu_2  = mu_2_vec[i]
    )
    
    cat("CCC for variable",i,":",
        round(True_CCC_i_value,3),"\n")
}
```

# calculate CCCM

```{r}
for(i in 1:length(rho_c_vec)){
    rho_c = rho_c_vec[i]
    
    tmp_M = rbind(mu_1_vec,mu_2_vec)
    tmp_U = matrix(
        c(sigma_sq_1,
          sqrt(sigma_sq_1)*sqrt(sigma_sq_2)*rho_r,
          sqrt(sigma_sq_1)*sqrt(sigma_sq_2)*rho_r,
          sigma_sq_2),
        nrow=2, ncol=2)
    tmp_V = sqrt(tau_sq_vec) %*% t(sqrt(tau_sq_vec)) * rho_c; diag(tmp_V) = tau_sq_vec
    
    True_CCCM_value <- True_CCCM(M=tmp_M, U=tmp_U, V=tmp_V)
    
    cat("True CCCM for rho_c =", rho_c, ":",
        round(True_CCCM_value,3), "\n")
    }
```
